local load = require("spec.load")
local Wire = load("net/Wire")
local Verify = load("net/Verify")
local Board = load("net/Board")

local DAY = 20733
local NOW = DAY * 86400 + 3600 * 15

local function rec(p, n, e, d, extra)
  local r = { p = p, c = "HUNTER", n = n, e = e or NOW, d = d or DAY, u = (n - 1) * 0.9, g = 0.7 }
  for k, v in pairs(extra or {}) do r[k] = v end
  return r
end

describe("Wire", function()
  it("round-trips records and relays", function()
    local r = rec("Ann-Realm", 42)
    local kind, back = Wire.decode(Wire.record(r), "Ann-Realm")
    assert.equal("R", kind)
    assert.equal(42, back.n); assert.equal(NOW, back.e); assert.equal(DAY, back.d); assert.equal("HUNTER", back.c)
    assert.near(0.7, back.g, 1e-9); assert.near(36.9, back.u, 1e-9)
    kind, back = Wire.decode(Wire.relay(r), "Bob-Realm")
    assert.equal("S", kind); assert.equal("Ann-Realm", back.p)
    kind, back = Wire.decode(Wire.test(r), "Ann-Realm")
    assert.equal("T", kind); assert.equal(42, back.n); assert.equal("Ann-Realm", back.p)
  end)

  it("decodes queries and heartbeats, rejects junk", function()
    assert.equal("Q", (Wire.decode(Wire.query(), "x")))
    local kind, class = Wire.decode(Wire.heartbeat("MAGE"), "x")
    assert.equal("H", kind); assert.equal("MAGE", class)
    assert.is_nil(Wire.decode("R|2|HUNTER|1|2|3|4|5", "x"))
    assert.is_nil(Wire.decode("R|1|HUNTER|abc|2|3|4|5", "x"))
    assert.is_nil(Wire.decode("S|1|bad name|HUNTER|20|2|3|4|5", "x"))
    assert.is_nil(Wire.decode(string.rep("a", 300), "x"))
    assert.is_nil(Wire.decode(nil, "x"))
  end)
end)

describe("Verify", function()
  it("accepts a plausible live record", function()
    assert.is_true(Verify.record(rec("A", 50, NOW - 5), NOW, DAY, true))
  end)

  it("rejects implausible ones", function()
    assert.same({ false, "length" }, { Verify.record(rec("A", 10), NOW, DAY, true) })
    assert.same({ false, "gap" }, { Verify.record(rec("A", 50, nil, nil, { g = 0.2 }), NOW, DAY, true) })
    assert.same({ false, "too fast" }, { Verify.record(rec("A", 50, nil, nil, { u = 5 }), NOW, DAY, true) })
    assert.same({ false, "too slow" }, { Verify.record(rec("A", 50, nil, nil, { u = 200 }), NOW, DAY, true) })
    assert.same({ false, "future" }, { Verify.record(rec("A", 50, NOW + 600), NOW, DAY, true) })
    assert.same({ false, "stale" }, { Verify.record(rec("A", 50, NOW - 600), NOW, DAY, true) })
    assert.same({ false, "day mismatch" }, { Verify.record(rec("A", 50, NOW - 600, DAY - 5), NOW, DAY, false) })
  end)

  it("accepts old relayed records", function()
    local old = NOW - 86400 * 20
    assert.is_true(Verify.record(rec("A", 50, old, DAY - 20), NOW, DAY, false))
  end)
end)

describe("Board", function()
  it("keeps first-hand records, best per player and day", function()
    local s = Board.ensure()
    assert.is_true(Board.addFirstHand(s, rec("A", 30)))
    assert.is_false(Board.addFirstHand(s, rec("A", 20)))
    assert.is_true(Board.addFirstHand(s, rec("A", 40)))
    Board.addFirstHand(s, rec("A", 90, NOW - 86400 * 3, DAY - 3))
    local today = Board.top(s, DAY, 1)
    assert.equal(1, #today); assert.equal(40, today[1].n)
    assert.equal(90, Board.top(s, DAY, 7)[1].n)
  end)

  it("needs two distinct relayers, and never the player", function()
    local s = Board.ensure()
    local r = rec("A", 33)
    assert.is_false(Board.addRelayed(s, r, "A", NOW))
    assert.is_false(Board.addRelayed(s, r, "B", NOW))
    assert.is_false(Board.addRelayed(s, r, "B", NOW))
    assert.equal(0, #Board.top(s, DAY, 1))
    assert.equal(1, Board.relays(s, r))
    assert.is_true(Board.addRelayed(s, r, "C", NOW))
    assert.equal(33, Board.top(s, DAY, 1)[1].n)
  end)

  it("ranks, filters online and picks records to sync", function()
    local s = Board.ensure()
    Board.addFirstHand(s, rec("A", 30)); Board.addFirstHand(s, rec("B", 50)); Board.addFirstHand(s, rec("C", 40))
    local top = Board.top(s, DAY, 1)
    assert.same({ "B", "C", "A" }, { top[1].p, top[2].p, top[3].p })
    local online = Board.online({ A = NOW - 10, B = NOW - 700 }, NOW)
    local list = Board.top(s, DAY, 1, online)
    assert.equal(1, #list); assert.equal("A", list[1].p)
    local sync = Board.forSync(s, DAY, 2, "B")
    assert.equal(2, #sync); assert.equal("C", sync[1].p)
  end)

  it("prunes old days and stale relays", function()
    local s = Board.ensure()
    Board.addFirstHand(s, rec("A", 30, NOW - 86400 * 400, DAY - 400))
    Board.addRelayed(s, rec("B", 30), "C", NOW - 4000)
    Board.prune(s, DAY, NOW)
    assert.is_nil(next(s.records)); assert.is_nil(next(s.pending))
  end)

  it("remembers peers, forgets the oldest and the long gone", function()
    local s = Board.ensure()
    for i = 1, Board.PEERS_MAX + 1 do Board.notePeer(s, "P" .. i, NOW + i) end
    assert.is_nil(s.peers.P1); assert.equal(NOW + 2, s.peers.P2)
    assert.same({ "P201", "P199" }, Board.peersToAsk(s, { P200 = true }, 2))
    s.peers.P2 = NOW - Board.PEERS_KEEP - 1
    Board.prune(s, DAY, NOW)
    assert.is_nil(s.peers.P2); assert.is_not_nil(s.peers.P3)
  end)
end)
