local load = require("spec.load")
local Stats = load("Stats")

describe("Stats", function()
  it("numbers days", function()
    assert.equal(0, Stats.dayNumber(1970, 1, 1))
    assert.equal(20733, Stats.dayNumber(2026, 10, 7))
    assert.equal(Stats.dayNumber(2024, 3, 1) - 1, Stats.dayNumber(2024, 2, 29))
  end)

  it("counts jumps and streaks per day and all time", function()
    local s = Stats.new()
    for _ = 1, 5 do Stats.addJump(s, 100) end
    Stats.endStreak(s, 100, 5)
    Stats.endStreak(s, 100, 1)
    Stats.addJump(s, 101)
    assert.equal(6, s.jumps); assert.equal(1, s.streaks)
    assert.same({ 5, 1, 5 }, { Stats.today(s, 100) })
    assert.same({ 1, 0, 0 }, { Stats.today(s, 101) })
    assert.same({ 0, 0, 0 }, { Stats.today(s, 102) })
  end)

  it("flags NEW BEST only above x10", function()
    local s = Stats.new()
    assert.is_false((Stats.endStreak(s, 1, 8)))
    assert.equal(8, s.best)
    local nb, prev = Stats.endStreak(s, 1, 11)
    assert.is_true(nb); assert.equal(8, prev)
    assert.is_false((Stats.endStreak(s, 1, 11)))
    nb, prev = Stats.endStreak(s, 1, 30)
    assert.is_true(nb); assert.equal(11, prev)
  end)

  it("flags BEST TODAY when only today's best is beaten", function()
    local s = Stats.new()
    Stats.endStreak(s, 1, 40)                       -- all-time 40
    local nb, _, tb, prevToday = Stats.endStreak(s, 2, 15)
    assert.is_false(nb); assert.is_true(tb); assert.equal(0, prevToday)
    nb, _, tb, prevToday = Stats.endStreak(s, 2, 20)
    assert.is_false(nb); assert.is_true(tb); assert.equal(15, prevToday)
    nb, _, tb = Stats.endStreak(s, 2, 18)
    assert.is_false(nb); assert.is_false(tb)
    nb, _, tb = Stats.endStreak(s, 2, 50)            -- all-time wins, not both
    assert.is_true(nb); assert.is_false(tb)
    _, _, tb = Stats.endStreak(s, 3, 9)              -- x10 and below never count
    assert.is_false(tb)
  end)

  it("computes period bests", function()
    local s = Stats.new()
    Stats.endStreak(s, 100, 40)
    Stats.endStreak(s, 120, 20)
    Stats.endStreak(s, 126, 9)
    assert.equal(9, Stats.periodBest(s, 126, 1))
    assert.equal(20, Stats.periodBest(s, 126, 7))
    assert.equal(40, Stats.periodBest(s, 126, 30))
    assert.equal(20, Stats.periodBest(s, 130, 30))
  end)

  it("prunes old days and repairs saved tables", function()
    local s = Stats.ensure({ jumps = "3", days = { [1] = { j = 1, s = 0, b = 0 }, [500] = { j = 2, s = 0, b = 0 } } })
    assert.equal(3, s.jumps); assert.equal(0, s.best)
    Stats.prune(s, 500)
    assert.is_nil(s.days[1]); assert.is_not_nil(s.days[500])
  end)
end)
