local load = require("spec.load")
local Streak = load("Streak")

describe("Streak", function()
  it("counts jumps inside the 3 s window", function()
    local s = Streak.new()
    assert.equal(1, (s:jump(10)))
    assert.equal(2, (s:jump(12.9)))
    assert.equal(3, (s:jump(15.9)))
  end)

  it("ends after 3 s without a jump", function()
    local s = Streak.new()
    s:jump(0); s:jump(1)
    assert.is_nil(s:tick(4))
    local ended = s:tick(4.01)
    assert.same({ n = 2, startedAt = 0, endedAt = 1 }, ended)
    assert.is_false(s:active())
  end)

  it("a late jump ends the old streak and starts a new one", function()
    local s = Streak.new()
    s:jump(0); s:jump(1); s:jump(2)
    local n, ended = s:jump(9)
    assert.equal(1, n)
    assert.equal(3, ended.n)
  end)

  it("reports idle time", function()
    local s = Streak.new()
    assert.is_nil(s:idle(5))
    s:jump(5)
    assert.equal(1.5, s:idle(6.5))
  end)
end)
