local load = require("spec.load")
local Tiers = load("Tiers")

describe("Tiers", function()
  it("assembles the ribbon over x1-x20", function()
    local l = Tiers.look(3)
    assert.near(0.6, l.core, 1e-9); assert.equal(0, l.mid); assert.equal(0, l.sides)
    l = Tiers.look(8)
    assert.equal(1, l.core); assert.near(0.6, l.mid, 1e-9); assert.is_false(l.trimMid)
    l = Tiers.look(10)
    assert.equal(1, l.mid); assert.is_true(l.trimMid); assert.equal(0, l.sides)
    l = Tiers.look(15)
    assert.near(0.5, l.sides, 1e-9); assert.is_false(l.trimSide)
    assert.is_true(Tiers.look(20).trimSide)
  end)

  it("switches lettering at x7", function()
    assert.is_false(Tiers.look(6).extruded)
    assert.is_true(Tiers.look(7).extruded)
  end)

  it("picks tiers and effects", function()
    assert.equal(1, Tiers.index(24)); assert.equal(2, Tiers.index(25))
    assert.equal(3, Tiers.index(50)); assert.equal(4, Tiers.index(199)); assert.equal(5, Tiers.index(5000))
    assert.equal(0, Tiers.effects(24)); assert.equal(4, Tiers.effects(200))
  end)

  it("grows 0.1% per jump up to +300%", function()
    assert.near(1.1, Tiers.growth(100), 1e-9)
    assert.near(2.0, Tiers.growth(1000), 1e-9)
    assert.near(4.0, Tiers.growth(3000), 1e-9)
    assert.near(4.0, Tiers.growth(9000), 1e-9)
  end)

  it("names events", function()
    assert.equal("stage", Tiers.event(5)); assert.equal("stage", Tiers.event(10)); assert.equal("stage", Tiers.event(20))
    assert.equal("tier", Tiers.event(25)); assert.equal("tier", Tiers.event(200))
    assert.is_nil(Tiers.event(26))
    assert.equal("ornament", Tiers.event(75)); assert.equal("ornament", Tiers.event(150))
    assert.equal("ornament", Tiers.event(300))
    assert.equal("pulse", Tiers.event(30)); assert.equal("pulse", Tiers.event(60)); assert.equal("pulse", Tiers.event(1000))
  end)

  it("adds ornaments at x75, x150, x300", function()
    assert.equal(0, Tiers.look(74).ornaments); assert.equal(1, Tiers.look(75).ornaments)
    assert.equal(2, Tiers.look(150).ornaments); assert.equal(3, Tiers.look(9999).ornaments)
  end)

  it("tints the face 20% toward the glow", function()
    local f = Tiers.look(30).face
    assert.near(1 - 0.2 * (1 - 0x1e / 255), f[1], 1e-9)
    assert.near(1, f[2], 1e-9)
  end)
end)
